### ISSUE TITLE
App Crashing

### ISSUE THREAD

**Issue by vmk0102** [florent37/SingleDateAndDayPicker#321]
I tried to implement doubledatetimepicker dialog on button click but get the follow errror:

```
2021-06-18 23:59:48.029 13072-13072/com.dabbssolutions.tryflorentdate E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.dabbssolutions.tryflorentdate, PID: 13072
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.github.florent37.singledateandtimepicker.SingleDateAndTimePicker.setTimeZone(java.util.TimeZone)' on a null object reference
        at com.github.florent37.singledateandtimepicker.dialog.DoubleDateAndTimePickerDialog.setTimeZone(DoubleDateAndTimePickerDialog.java:427)
        at com.github.florent37.singledateandtimepicker.dialog.DoubleDateAndTimePickerDialog.access$700(DoubleDateAndTimePickerDialog.java:30)
        at com.github.florent37.singledateandtimepicker.dialog.DoubleDateAndTimePickerDialog$Builder.build(DoubleDateAndTimePickerDialog.java:736)
        at com.github.florent37.singledateandtimepicker.dialog.DoubleDateAndTimePickerDialog$Builder.display(DoubleDateAndTimePickerDialog.java:755)
        at com.dabbssolutions.tryflorentdate.MainActivity$1.onClick(MainActivity.java:41)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2021-06-18 23:59:48.036 13072-13072/com.dabbssolutions.tryflorentdate I/Process: Sending signal. PID: 13072 SIG: 9

```

**Comment by mdave0905** [comment]
Same here, please help!
